### ISSUE TITLE
The Twitter feed on Firefox does not show, only the link to it does.

### ISSUE THREAD

**Issue by jgujgu** [indiesquidge/turing-dungeon#20]
The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.The Twitter feed on Firefox does not show, only the link to it does.

**Comment by indiesquidge** [comment]
![screen shot 2015-04-28 at 3 18 21 pm](https://cloud.githubusercontent.com/assets/3409645/7380578/ea66c394-edb9-11e4-8eec-9ed1ce8d5813.png)
Works for me. You must just suck `¯\_(ツ)_/¯`
